# Generated by Django 4.2.3 on 2024-02-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Aadhar_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
